{% set name = "containerpilot" %}
{% set version = "3.8.0" %}
{% set sha1 = "b10b30851de1ae1c095d5f253d12ce8fe8e7be17" %}
{% set sha256 = "8fbfb68ef02aefdcadbc414f7a47b8676dd8dc06d33b0eb78b26063d0a3b7bb2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/joyent/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha1: {{ sha1 }}
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - cp {{ name }} $PREFIX/bin
  skip: True  # [ not linux ]

test:
  commands:
    - containerpilot -version

about:
  home: https://www.joyent.com/containerpilot
  license: MPL-2.0
  license_family: OTHER
  summary: 'A service for autodiscovery and configuration of applications running in containers'

  # The remaining entries in this section are optional, but recommended
  description: |
      ContainerPilot is an init system designed to live inside the container. It acts as a
      process supervisor, reaps zombies, run health checks, registers the app in the service
      catalog, watches the service catalog for changes, and runs your user-specified code at
      events in the lifecycle of the container to make it all work right. ContainerPilot uses
      Consul to coordinate global state among the application containers.
  doc_url: https://www.joyent.com/containerpilot/docs
  dev_url: https://github.com/joyent/containerpilot

extra:
  recipe-maintainers:
    - sodre
