travis:
  secure:
    BINSTAR_TOKEN: FsFlCYYaxxPP6685tIXq2OvzA3/4vOUahqyMlNgA7qyfevHGw4hxb189gDCnon2t6XreG7XNtqq2TiZc2764xKwNDlM5tD9z3cpvRldhcclf+anyD3Pf7iayOvTy8qVnI2YGWY0VgoVQd75pR48hMuzCNWBX5cW2xfDEZTCcOOYH0C13Hqs4WcwIrfyHiYjx+SdY6EtcQ8ihEneXaUkukIZ71tiUjETXltd30YTglSk8KkNwTWmdRxyYpVyc6r2E6SHhDDPSPUgsNBw7cp1pvn+PrjpTfGUZKBnnGiPkLUT30PG88zdHZhGA2Ev/7lRImZtBYPrtLxEbZgI4gQIji/678X1i5mzdGpyxewocad0PpdO+jPZOuulQh6JAFAWEBjfk8CDwy8VJSQkleEwynS54D24OGV3MGYq4YcQTURvQtls96hqJUuqEBE9wipFuNTfsKrQaoQ0goFOPtaQATFrmkJvFjaB7i6vaWtBJgA/KQzIkxrg89sWbyaNz97xDfoZCUmPHtvpv2CwkJe5s15VQ7HOOgRrk+atAH9ACkQtFmsslF6g0Se5LDCj3zIK7yjYqpolAxHUdSeFNY77mOmBWTJ02gDB5I8+0pegZnRaOC+8ScwjaH4uU4zwZZ33TG9KwPheQIXxuTB7jt3pRd6cXr6F5DgAka5UdNnhk8c8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
