travis:
  secure:
    BINSTAR_TOKEN: HTRrYP28P+pXNuv7thOKNy178z2t3ALeSvk3IoewwpNEEJ03xAoVRLmDRPPW3D81CuUBvtqw7lf/ovABKv9X7kQEVvTguYJmLfLh5c/UuvhnpXpSD7UvLYCag+C0/QcmrKxdUMFco3Xp/4RG5jt0qUO2GI0wbO0aVJ66eMj78R7yX1oV8RoGfz9tlD3iCvje6M1dCW7lEiITW2sPaDfxmQqd5IFIR/Ud2PgUlT5JxhI1lFmeSRYYIzQIfvcuoP6MGwOe4+KsxyAgFs6ypxIvi/CC0l5oJghZIEajoDcQUH0wy4Xjgt/N6UHKtKh4YFoKiAXYg3GIv58bF9jJa4rs/gLtgjrCu7Nlte4Tyhr6vazeNUakd5OnM5rK5F8eXtHKWQMedZwIweavLedK621HDChVDW01M1K6TQKHiY0+ithcmCuVYrJ+SP5YSK44Y2QEM+Bctl1mBgrjQ0kTpDaK5DwglIz1LWXsnM1vsP05C2CbJK2j/wQycnPjyZnWJaL+qqi81SBdNz68byPSiPAHEkMRzviwGkOfpCELNttp/Rfy2g3XPK4MKyJoJ9Gmu28Yfnb62UuAxRINHiZVb3ES5n+cTgaxLY+1vZLW3YfiBQ8cMgzoSKjs33QkG5sQ4Eq5JhAVN/FtqsGsBrlnVsK/mkCU3HJxdul7HJm6F08w0s0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
